"""empty message

Revision ID: 8416353914da
Revises: 16ab1db719cf
Create Date: 2025-06-24 21:37:58.986475

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8416353914da'
down_revision = '16ab1db719cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('imgcarousel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('food', schema=None) as batch_op:
        batch_op.add_column(sa.Column('allergens', sa.String(length=200), nullable=True))
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('food', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.VARCHAR(length=200), nullable=True))
        batch_op.drop_column('allergens')

    op.drop_table('imgcarousel')
    # ### end Alembic commands ###
