"""empty message

Revision ID: ce6b0bc7852c
Revises: 081184441065
Create Date: 2025-06-29 21:19:57.954080

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce6b0bc7852c'
down_revision = '081184441065'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('imgcarousel', schema=None) as batch_op:
        batch_op.add_column(sa.Column('position', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('imgcarousel', schema=None) as batch_op:
        batch_op.drop_column('position')

    # ### end Alembic commands ###
